### ISSUE TITLE
Why lambda layers?

### ISSUE THREAD

**Issue by Zweer** [Envek/aws-sam-typescript-layers-example#5]
Hi,

I've found your repo while searching for typescript + lambda layers...
At first your approach was perfect, but then I noticed something your article confirmed: it looks like the lambda layers are useless because all the code is in your functions, isn't it?
Requiring the common library with the relative path makes them being compiled by typescript... which means being copied inside the function folder... so what's the meaning of using layers?? I expected to have only the function code and the layers in other folders (requiring them with /opt/nodejs/utils...)

Am i missing something??

Thanks a lot

**Comment by Envek** [comment]
In this example lambda layers contains _dependencies_ while functions itself contains _application code_.

In contrast with webpack (and tools alike it), `tsc` does not bundle code from `node_modules` into final result.

You can run `sam build` and confirm that all heavy things are gone to the shared layer:
```
$ du -b -h -d 1 .aws-sam/build | sort -h -r

57M	.aws-sam/build
56M	.aws-sam/build/RuntimeDependenciesLayer
21K	.aws-sam/build/getByIdFunction
21K	.aws-sam/build/getAllItemsFunction
20K	.aws-sam/build/writeItemFunction
20K	.aws-sam/build/putItemFunction
```

And this speeds deploys a lot, especially when you have dozens of functions (see https://github.com/aws/aws-sam-cli/issues/2626#issuecomment-782584090 for example) just because you don't need to upload literally gigabytes of repeated `node_modules` content.

I don't see much value in moving _shared application code_ into layers because it is usually just a few kilobytes and won't make any noticeable difference. (And, to be honest, I haven't even looked on how to accomplish that).

And, of course, we can easily create one more layer that can contain shared static files or things like that, if needed. Just add one more entry into `template.yml` and one more target into `Makefile`.

I'm

**Comment by Zweer** [comment]
Hey, thanks for the reply!
No problem, I think we've opposite views of the same thing =)
What I'm trying to do is having one big layer with all my "common code" (with deps) while every single function has its own code (with deps), but nothing about the common code...

But I think you've not explored this scenario...

BTW thanks a lot!

**Comment by Envek** [comment]
Feel free to explore and create a pull request :wink: 

However, I believe it is better to make two separate layers: one with dependencies and one with common code. As common code changes more frequently and weights less than node_modules, placing it in different layer will also speed up deploys (and yes, Lambda function can attach more than one layer).

**Comment by brandonhall** [comment]
Thank you @Envek. Thank you so much for this repo and these examples. It's the "least hacky" version I found and the code is much appreciated.
